AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Creates the ECS Cluster and the ALB.

####################
# Parameters section
####################

Parameters:

  ClusterSecurityGroupIds:
    Description: Security group/s for the cluster.
    Type: CommaDelimitedList

  ALBSecurityGroupIds:
    Description: Security group/s for the ALB.
    Type: CommaDelimitedList

  VpcId:
    Type: String
    Description: ID of an existing VPC in which to launch your container instances
    AllowedPattern: ^(?:vpc-[0-9a-f]{8,17}|)$
    ConstraintDescription: VPC Id must begin with 'vpc-' and have a valid uuid

  SubnetIds:
    Type: CommaDelimitedList
    Description: Comma separated list of existing VPC Subnet Ids where ECS instances will run

  LatestECSOptimizedAMI:
    Description: AMI ID
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ecs/optimized-ami/amazon-linux-2023/recommended/image_id

  IAMProfile:
    Description: PREVIOUSLY existing IAM Instance Profile
    Type: String
    Default: LabInstanceProfile

  IAMRoleName:
    Description: IAM role used for task execution
    Type: String
    Default: LabRole

###################
# Resources section
###################

Resources:

  ## Cluster

  ECSLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    DependsOn: ECSCluster
    Properties:
      LaunchTemplateName: proy-ECSLaunchTemplate
      LaunchTemplateData:
        ImageId: !Ref LatestECSOptimizedAMI
        NetworkInterfaces:
          - AssociatePublicIpAddress: true
            DeviceIndex: 0
            DeleteOnTermination: true
            Groups: !Ref ClusterSecurityGroupIds
        InstanceType: t2.micro
        IamInstanceProfile:
          Arn: !Sub arn:aws:iam::${AWS::AccountId}:instance-profile/${IAMProfile}
        UserData: !Base64
          Fn::Sub:
            - |-
              #!/bin/bash
              echo ECS_CLUSTER=${ClusterName} >> /etc/ecs/ecs.config;
            - ClusterName: proy-cluster

  ECSAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    DependsOn: ECSCluster
    Properties:
      MinSize: 3
      MaxSize: 9
      DesiredCapacity: 3
      LaunchTemplate:
        LaunchTemplateId: !Ref ECSLaunchTemplate
        Version: !GetAtt ECSLaunchTemplate.LatestVersionNumber
      VPCZoneIdentifier: !Ref SubnetIds
      Tags:
        - Key: Name
          PropagateAtLaunch: true
          Value: proy-cluster's ECS Instance

  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: proy-cluster
      ClusterSettings:
        - Name: containerInsights
          Value: disabled
      ServiceConnectDefaults:
        Namespace: proy-cluster
      Tags:
        - Key: cluster-ecs
          Value: proy

  EC2CapacityProvider:
    Type: AWS::ECS::CapacityProvider
    Properties:
      AutoScalingGroupProvider:
        AutoScalingGroupArn: !Ref ECSAutoScalingGroup
        ManagedScaling:
          Status: ENABLED
          TargetCapacity: 100
        ManagedTerminationProtection: DISABLED

  ClusterCPAssociation:
    Type: AWS::ECS::ClusterCapacityProviderAssociations
    DependsOn: ECSCluster
    Properties:
      Cluster: proy-cluster
      CapacityProviders:
        - !Ref EC2CapacityProvider
      DefaultCapacityProviderStrategy:
        - Base: 0
          Weight: 1
          CapacityProvider: !Ref EC2CapacityProvider

  ## Task

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: proy-task
      Cpu: 250
      Memory: 330
      NetworkMode: awsvpc
      TaskRoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/${IAMRoleName}
      ExecutionRoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/${IAMRoleName}
      ContainerDefinitions:
        - Name: proy_flask_container
          Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/proyrepo:proy_flask_container
          Cpu: 250
          Memory: 330
          PortMappings:
            - ContainerPort: 80
              Protocol: tcp

  ## Service

  ECSService:
    Type: AWS::ECS::Service
    DependsOn:
      - ALB
      - ALBListener
      - TargetGroup
    Properties:
      Cluster: !Ref ECSCluster
      TaskDefinition: !Ref TaskDefinition
      LaunchType: EC2
      DesiredCount: 3
      LoadBalancers:
        - ContainerName: proy_flask_container
          ContainerPort: 80
          TargetGroupArn: !Ref TargetGroup
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets: !Ref SubnetIds
          SecurityGroups: !Ref ClusterSecurityGroupIds

  ## Target Group

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: proy-dest-grp
      Protocol: HTTP
      Port: 80
      VpcId: !Ref VpcId
      TargetType: ip
      HealthCheckEnabled: true
      HealthCheckIntervalSeconds: 6
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      HealthCheckPath: /health
      Matcher:
        HttpCode: 200
      Tags:
        - Key: Name
          Value: proy-dest-grp

  ## ALB

  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: proy-alb
      Scheme: internet-facing
      SecurityGroups: !Ref ALBSecurityGroupIds
      Subnets: !Ref SubnetIds
      Type: application
      IpAddressType: ipv4
      Tags:
        - Key: Name
          Value: proy-alb

  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ALB
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
