AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Creates the neccesary bucket, lambda function, DynamoDB table, and SNS topic.

####################
# Parameters section
####################

Parameters:
  IAMRoleName:
    Description: IAM role used for the lambda function
    Type: String
    Default: LabRole

  EmailTarget:
    Description: Email addresss used by SNS
    Type: String
    Default: dayana.quispe@edu.upct.es

###################
# Resources section
###################

Resources:

  ## Bucket

  LandingZoneBucket:
    Type: AWS::S3::Bucket
    DependsOn: LambdaPermission
    Properties:
      BucketName: !Sub proy-landing-${AWS::AccountId}-${AWS::Region}
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:*
            Function: !GetAtt LambdaFunction.Arn

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    DependsOn: LandingZoneBucket
    Properties:
      Bucket: !Ref LandingZoneBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action:
              - "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::${LandingZoneBucket}/*"

  ## Lambda

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: proy-lambda
      Handler: index.lambda_handler
      Runtime: python3.12
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/${IAMRoleName}
      Code:
        ZipFile: |
          import boto3

          def lambda_handler(event, context):
            # Aquí va el código de Dayana
            pass

  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt LambdaFunction.Arn
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceAccount: !Ref AWS::AccountId

  ## DynamoDB

  # YearMonth | Day | Mean | Deviation
  #
  # YearMonth = 100 * Year + Month

  DynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: proy-stats
      AttributeDefinitions:
        - AttributeName: YearMonth
          AttributeType: N
        - AttributeName: Day
          AttributeType: N
      KeySchema:
        - AttributeName: YearMonth
          KeyType: HASH   # Partition Key
        - AttributeName: Day
          KeyType: RANGE  # Sort Key
      BillingMode: PAY_PER_REQUEST

  # SNS

  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: proy-sns
      Subscription:
        - Endpoint: !Ref EmailTarget
          Protocol: email
